please review and suggest necessary changes
marsiitr/Air-Hockey-Robot pull request #2
Opened 2020-07-28 17:17 UTC by naman99-agar

2020-07-28 18:20 UTC, SanjeevKrishnan requested changes
@naman99-agar Changes Required!
1. Rename "Images and Video" as "Images and Videos". Similarly, Rename Video as "Videos".
2. Move CAD images into Mechanical Design. You can have full view CAD Images inside Images folder if you don't have other project related images.
3. Justify text in Report.
4. In README.md, remove heading "Images" and have only one picture at the top.
5. In README.md, Arduino code has to be a sub-heading under main heading "Electronics Aspect of Bot"
6. In README.md, move workflow above Mechanical Aspcet.
7. In README.md, hyperlink team members and mentors names with their GitHub profile link.
8. In README.md, justify text using HTML tags.

2020-07-29 10:02 UTC, Shubhanshu07 commented on README.md
> +1. Mohit Singh (https://github.com/mohitschoudhary)
@naman99-agar 
Syntax is wrong it should be `` [Mohit Singh](https://github.com/mohitschoudhary)``  [Mohit Singh] which gives (https://github.com/mohitschoudhary)
Do this for all the names

2020-07-29 13:32 UTC, naman99-agar commented
the changes are done, please review

2020-07-29 13:40 UTC, SanjeevKrishnan requested changes
@naman99-agar Minor Changes

2020-07-29 13:40 UTC, SanjeevKrishnan commented on README.md
> +## Image of the project
Remove this sub-heading and remove '1.' at the beginning from "1. Table isometric view"

2020-07-29 13:40 UTC, SanjeevKrishnan commented on README.md
> +<p align="justify">To create an autonomous gaming system of air hockey where one player is human and other side will be played by a bot. The bot will automatically detect the position of the moving p
When you start a paragraph with <p> tag you should end it with <\p>. For example `<p align="justify">Sample Text<\p>`. Do this change throughout README.md

2020-07-29 13:40 UTC, SanjeevKrishnan commented on README.md
> +1. Tabish Madni (https://github.com/Tmadni)
Do the same syntax change in Mentors list too which you did for Team Members

2020-07-30 02:15 UTC, naman99-agar commented
please review

2020-07-30 02:53 UTC, SanjeevKrishnan approved these changes
@naman99-agar PR looks fine!
@Shubhanshu07 I suggest for merge!

2020-07-30 10:49 UTC, Shubhanshu07 commented
@Great work PR looks good to  me

2020-07-30 10:49 UTC, merged